In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn; seaborn.set_style('whitegrid')
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm

from scipy.stats import norm
from sklearn.mixture import GaussianMixture
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KernelDensity

from citableclass import Citable
from corpussearch import search

import ephem

In [2]:
cite=Citable("BAAP00028", formats="et")
pyephembsc = []
reader=cite.csv()
for row in reader:
    pyephembsc.append(row)
starcatalogue=pd.DataFrame(pyephembsc, columns=['star', "","","",'magnitude',"",""])
#change string to float
starcatalogue['magnitude'] = starcatalogue['magnitude'].astype('float64')
starcatalogue.head(10)

       star                                              magnitude
0    Sirrah  f|S|B9  0:08:23.2|135.68  29:05:27|-162.95       2.07  2000  0
1      Caph  f|S|F2  0:09:10.1|523.39  59:09:01|-180.42       2.28  2000  0
2   Algenib  f|S|B2     0:13:14.2|4.7    15:11:01|-8.24       2.83  2000  0
3   Schedar  f|S|K0   0:40:30.4|50.36   56:32:15|-32.17       2.24  2000  0
4    Mirach  f|S|M0  1:09:43.8|175.59  35:37:15|-112.23       2.07  2000  0
5  Achernar  f|S|B3   1:37:42.8|88.02  -57:14:12|-40.08       0.45  2000  0
6    Almach  f|S|B8   2:03:53.9|43.08   42:19:48|-50.85       2.10  2000  0
7     Hamal  f|S|K2  2:07:10.3|190.73  23:27:46|-145.77       2.01  2000  0
8   Polaris  f|S|F7   2:31:47.1|44.22   89:15:51|-11.74       1.97  2000  0
9    Menkar  f|S|M2  3:02:16.8|-11.81    4:05:24|-78.76       2.54  2000  0

In [3]:
brightstars=list(starcatalogue["star"][starcatalogue["magnitude"] < 1.2])

In [4]:
dict_stars={}
for element in brightstars:
    dec_val={}
    declinationlist=list()
    for year in ['-5000', '-4800', '-4600', '-4400', '-4200', '-4000']:
        try:
            star=ephem.star(element, year+'/01/01', epoch=ephem.J2000 )
            dec_val[year]=np.rad2deg(float(star.a_dec))
        except:
            pass
    if len(dec_val)!=0:
        dict_stars[element]=dec_val

In [5]:
df_stars=pd.DataFrame(dict_stars)
df_stars

,Achernar,Aldebaran,Rigel,Capella,Betelgeuse,Canopus,Sirius,Procyon,Pollux,Spica,Agena,Arcturus,Antares,Vega,Altair,Fomalhaut
-4000,-57.169896,16.825185,-8.200734,46.710741,7.388852,-52.735266,-14.675475,6.951050,28.102939,-11.108251,-60.331307,22.518107,-26.393278,38.304164,8.225213,-29.348363
-4200,-57.167670,16.835702,-8.200703,46.734464,7.388249,-52.736581,-14.607544,7.008512,28.105491,-11.106488,-60.329915,22.629156,-26.391989,38.288198,8.203799,-29.339242
-4400,-57.165444,16.846220,-8.200672,46.758187,7.387646,-52.737895,-14.539613,7.065974,28.108043,-11.104726,-60.328523,22.740204,-26.390700,38.272232,8.182386,-29.330122
-4600,-57.163217,16.856737,-8.200640,46.781910,7.387043,-52.739210,-14.471682,7.123435,28.110595,-11.102964,-60.327131,22.851253,-26.389411,38.256266,8.160973,-29.321001
-4800,-57.160991,16.867254,-8.200609,46.805633,7.386440,-52.740525,-14.403751,7.180897,28.113147,-11.101202,-60.325740,22.962302,-26.388122,38.240301,8.139560,-29.311880
-5000,-57.158765,16.877771,-8.200578,46.829357,7.385836,-52.741839,-14.335820,7.238359,28.115699,-11.099439,-60.324348,23.073350,-26.386832,38.224335,8.118146,-29.302759